# Generated by Django 5.0.7 on 2024-07-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qualification',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
