# Generated by Django 5.0.7 on 2024-07-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_category_image_category_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('race', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('direction', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
